#!/bin/bash

## Instala as dependencias do theme
## Usage:   fin start_front
## Parameters:
##      none

cd $PROJECT_ROOT

# WORKDIR /var/www/ into dockerfile

docker exec -it drupaldummy_front_1 sh -c "cd /var/www/docroot/themes/custom/salsa && npm run gulp build -- --exit"

