#!/bin/bash

## Faz setup básico do drupal para base do serve docksal e configura caches para livereload
## Usage:   fin config_drupal
## Parameters:
##      none

cd $PROJECT_ROOT

tar -xvzf configdev.tar.gz

echo "Necessária senha de sudo para mover alguns arquivos de config com permissões."
sudo mv development.services.yml docroot/sites/development.services.yml
sudo mv settings.local.php docroot/sites/default/settings.local.php
sudo mv settings.php docroot/sites/default/settings.php

rm configdev.tar.gz