#!/bin/bash

## Faz setup básico do drupal para base do serve docksal e configura caches para livereload
## Usage:   fin config_drupal
## Parameters:
##      none

cd $PROJECT_ROOT

# tar -xvzf configdev.tar.gz

echo "Necessária senha de sudo para mover alguns arquivos de config com permissões."

sudo cp configdev/development.services.yml docroot/sites/development.services.yml
sudo cp configdev/settings.local.php docroot/sites/default/settings.local.php
sudo cp configdev/settings.php docroot/sites/default/settings.php

sudo rm -rf configdev/

#rm configdev.tar.gz