#!/bin/bash

## Faz download do drupal 8.3.2 para o projeto
## Usage:   fin download_drupal
## Parameters:
##      none

cd $PROJECT_ROOT
mkdir docroot
# //https://ftp.drupal.org/files/projects/drupal-8.3.2.tar.gz
curl -O https://ftp.drupal.org/files/projects/drupal-8.3.2.tar.gz
tar -xvzf drupal-8.3.2.tar.gz 
mv  -v drupal-8.3.2/* docroot/
mv  -v drupal-8.3.2/.* docroot/

cd $PROJECT_ROOT
rm drupal-8.3.2.tar.gz
rm -rf drupal-8.3.2/
