#!/bin/bash

## Instala o theme Básico com stylus + babel ECMAscript6 + Browsersync with gulp
## Usage:   fin install_theme
## Parameters:
##      none

cd $PROJECT_ROOT
YELLOW='\e[0;33m';  
NC='\033[0m' # No Color

mkdir docroot/themes/custom

cd docroot/themes/custom

# // https://github.com/feliperohde/salse/releases
curl -L https://github.com/feliperohde/salse/tarball/v0.8.1 | tar zx

mv feliperohde-salse-*/ salsa/

echo -e "${YELLOW}Vá até a guia de aparência do drupal e habilite o D8Theme :)${NC}"
