#!/bin/bash

## Instala o theme Básico com stylus + babel ECMAscript6 + Browsersync with gulp
## Usage:   fin install_theme
## Parameters:
##      none

cd $PROJECT_ROOT

mkdir docroot/themes/custom

cd docroot/themes/custom

# // https://github.com/feliperohde/salse/releases
curl -L https://github.com/feliperohde/salse/tarball/v0.2 | tar zx

mv feliperohde-salse-32ed5c9/ salsa/
