#!/bin/bash

## Inicia um servidor local com watch
## Usage:   fin serve_front
## Parameters:
##      none

cd $PROJECT_ROOT
GREEN='\033[0;32m'
YELLOW='\e[0;33m';
NC='\033[0m' # No Color

command_exists () {
    type "$1" &> /dev/null ;
}


# if command_exists xdg-open ; then
# 	echo -e "${YELLOW}Abrindo uma aba no seu browswer preferido!...${NC}"
#     xdg-open "http://localhost:3000"
# fi

echo -e "${YELLOW}Criando um server local com proxy...${NC}"

docker exec -it ${PROJECT_NAME}_front_1 sh -c "cd /var/www/docroot/themes/custom/salsa && npm run gulp serve"