#!/bin/bash

## Inicia um servidor local com watch
## Usage:   fin serve_front
## Parameters:
##      none

cd $PROJECT_ROOT

open "http://localhost:3000"
docker exec -it drupaldummy_front_1 sh -c "cd /var/www/docroot/themes/custom/salsa && gulp serve"
