#!/bin/bash

## Instala as dependencias do theme e abre o sublime para ediçao
## Usage:   fin start_front
## Parameters:
##      none

command_exists () {
    type "$1" &> /dev/null ;
}

cd $PROJECT_ROOT

docker exec -it drupaldummy_front_1 sh -c "cd /var/www/docroot/themes/custom/salsa && npm install"

cd docroot/themes/custom/salsa

if command_exists subl ; then
    subl .
fi

