#!/bin/bash

## Instala as dependencias do theme e abre o sublime para ediçao
## Usage:   fin start_front
## Parameters:
##      none

command_exists () {
    type "$1" &> /dev/null ;
}

cd $PROJECT_ROOT

docker exec -it ${PROJECT_NAME}_front_1 sh -c "cd /var/www/docroot/themes/custom/salsa && npm install"